sudo: required
services:
  - docker

before_install:
  - docker build -t jmshie/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run jmshie/react-test npm test -- --coverage

after_success:
  - docker build -t jmshie/multi-client ./client
  - docker build -t jmshie/multi-nginx ./nginx
  - docker build -t jmshie/multi-server ./server
  - docker build -t jmshie/multi-worker ./worker
